// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ggkraultrvabiqynbkab.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdna3JhdWx0cnZhYmlxeW5ia2FiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg5MjY1ODgsImV4cCI6MjA3NDUwMjU4OH0.pI_fovnQg-0tpkhrkFQxao5eUQYynDgy_LL3mPw1Ti4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});